More install/uninstall mods, cli option tls_fp_file

diff --git a/install-sh b/install-sh
--- a/install-sh
+++ b/install-sh
@@ -41,6 +41,12 @@ MACOSX_CONFIGFILE=macosx.cfg
 ANONFILE=internal.net
 WATCHFILE=""
 KEYFILE=""
+TLS_FINGERPRINT_FILE=tls_fingerprint.json
+
+echo
+echo PCAP2FLOW INSTALL-SH
+echo --------------------
+echo
 
 # check command line arguments, ovveride defaults as appropirate
 #
@@ -116,47 +122,6 @@ if [ ! -f ${ANONFILE} ]; then
     exit
 fi
 
-if [ "${WATCHFILE}" == "" ]; then
-    # use the default malware watchfile
-    #
-    WATCHFILE=ip-filter.blf
-
-    # find a downloader program
-    command -v curl -h >/dev/null 2>&1
-    retval=$?
-    if [ $retval -ne "0" ]; then
-	command -v wget -h >/dev/null 2>&1
-	retval=$?
-	if [ $retval -ne "0" ]; then
-	    echo "error: did not find either curl or wget, cannot download $WATCHFILE"
-	    exit
-	else
-	    downloader=wget
-	fi
-    else
-	echo "found curl"
-	downloader=curl
-    fi
-    echo "using program $downloader"
-
-    # download the current public list of malware IP addresses from
-    # Talos (the Sourcefire/Cisco threat intelligence team) - note
-    # that this file changes daily, so don't rely on it if you don't
-    # update it - and install it as a malware watchlist file
-    # 
-    echo "downloading ip-filter.blf ... "
-    $downloader http://www.talosintel.com/feeds/ip-filter.blf -o ./ip-filter.blf
-    retval=$?
-    if [ $retval -ne "0" ]; then
-	echo "error: could not download ${WATCHFILE}"
-	exit
-    fi
-    if [ ! -f ${WATCHFILE} ]; then
-	echo "error: could not find watchfile ${WATCHFILE}"
-	exit
-    fi
-fi
-
 if [ "${KEYFILE}" == "" ]; then
     # set default name for upload key file 
     #
@@ -202,76 +167,25 @@ if [ "$sysname" == "Darwin" ]; then
     echo "found $sysname (Mac OS X), installing pcap2flow ..."
 
     # Create /usr/local/bin directory if it does not currently exist
-    if [ ! -d /usr/local/bin ]; then
-        mkdir /usr/local/bin
-        retval=$?
-        if [ $retval -ne "0" ]; then
-            echo "error: could not make directory /usr/local/bin"
-            exit
-        fi
-    else
-        echo "directory /usr/local/bin already exists"
-    fi
+    create_directory /usr/local/bin
 
     # Create /usr/local/var directory if it does not currently exist
-    if [ ! -d /usr/local/var ]; then
-        mkdir /usr/local/var
-        retval=$?
-        if [ $retval -ne "0" ]; then
-            echo "error: could not make directory /usr/local/var"
-            exit
-        fi
-    else
-        echo "directory /usr/local/var already exists"
-    fi
+    create_directory /usr/local/var
 
     # Create /usr/local/var/p2f directory if it does not currently exist
-    if [ ! -d /usr/local/var/p2f ]; then
-        mkdir /usr/local/var/p2f
-        retval=$?
-        if [ $retval -ne "0" ]; then
-            echo "error: could not make directory /usr/local/var/p2f"
-            exit
-        fi
-    else
-        echo "directory /usr/local/var/p2f already exists"
-    fi
+    create_directory /usr/local/var/p2f
+
+    # Create /usr/local/var/log directory if it does not currently exist
+    create_directory /usr/local/var/log
 
     # Create /usr/local/etc directory if it does not currently exist
-    if [ ! -d /usr/local/etc ]; then
-        mkdir /usr/local/etc
-        retval=$?
-        if [ $retval -ne "0" ]; then
-            echo "error: could not make directory /usr/local/etc"
-            exit
-        fi
-    else
-        echo "directory /usr/local/etc already exists"
-    fi
+    create_directory /usr/local/etc
 
     # Create /usr/local/etc/p2f directory if it does not currently exist
-    if [ ! -d /usr/local/etc/p2f ]; then
-        mkdir /usr/local/etc/p2f
-        retval=$?
-        if [ $retval -ne "0" ]; then
-            echo "error: could not make directory /usr/local/etc/p2f"
-            exit
-        fi
-    else
-        echo "directory /usr/local/etc/p2f already exists"
-    fi
+    create_directory /usr/local/etc/p2f
 
     # Create /usr/local/share directory if it does not currently exist
-    if [ ! -d /usr/local/share ]; then
-        mkdir /usr/local/share
-        retval=$?
-        if [ $retval -ne "0" ]; then
-            echo "error: could not make directory /usr/local/share"
-            exit
-        fi
-    else
-        echo "directory /usr/local/share already exists"
-    fi
+    create_directory /usr/local/share
 
     # Create /usr/local/share/man directory if it does not currently exist
     create_directory /usr/local/share/man
@@ -287,6 +201,15 @@ if [ "$sysname" == "Darwin" ]; then
         exit
     fi
 
+    # Install query
+    cp query.py /usr/local/bin/
+    retval=$?
+    if [ $retval -ne "0" ]; then
+        echo "error: could not copy to /usr/local/bin/"
+        exit
+    fi
+
+    # Install the macosx configuration file
     if [ -f /usr/local/etc/p2f/macosx.cfg ]; then
         echo "warning: file /usr/local/etc/p2f/macosx.cfg exists; renaming that file to macosx.cfg.bak"
         mv /usr/local/etc/p2f/macosx.cfg /usr/local/etc/p2f/macosx.cfg.bak 
@@ -295,6 +218,18 @@ if [ "$sysname" == "Darwin" ]; then
         retval=$?
         if [ $retval -ne "0" ]; then
             echo "error: could not copy ${MACOSX_CONFIGFILE} to /usr/local/etc/p2f"
+            exit
+        fi
+    fi
+
+    # Install the tls fingerprint file
+    if [ -f /usr/local/etc/p2f/${TLS_FINGERPRINT_FILE} ]; then
+        echo "file /usr/local/etc/p2f/${TLS_FINGERPRINT_FILE} exists; not installing tls fingerprint file"
+    else
+        cp ${TLS_FINGERPRINT_FILE} /usr/local/etc/p2f/
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not copy ${TLS_FINGERPRINT_FILE} to /usr/local/etc/p2f"
             exit
         fi
     fi
@@ -320,15 +255,18 @@ if [ "$sysname" == "Darwin" ]; then
     fi
     chmod 600 /usr/local/etc/p2f/${KEYFILE}
 
-    # Install the watch file
-    if [ -f /usr/local/etc/p2f/${WATCHFILE} ]; then
-        echo "file /etc/p2f/${WATCHFILE} exists; overwriting with recent file"
-    fi
-    cp ${WATCHFILE} /usr/local/etc/p2f/
-    retval=$?
-    if [ $retval -ne "0" ]; then
-        echo "error: could not copy ${WATCHFILE} to /usr/local/etc/p2f"
-        exit
+
+    if [ "${WATCHFILE}" != "" ]; then
+        # Install the watch file
+        if [ -f /usr/local/etc/p2f/${WATCHFILE} ]; then
+            echo "file /etc/p2f/${WATCHFILE} exists; overwriting with recent file"
+        fi
+        cp ${WATCHFILE} /usr/local/etc/p2f/
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not copy ${WATCHFILE} to /usr/local/etc/p2f"
+            exit
+        fi
     fi
 
     # Install the Launchd script for daemon management
@@ -348,12 +286,10 @@ if [ "$sysname" == "Darwin" ]; then
     fi
 
     ls -l /usr/local/bin/pcap2flow
-    ls -l /usr/local/etc/p2f/macosx.cfg
-    ls -l /usr/local/etc/p2f/${ANONFILE}
-    ls -l /usr/local/etc/p2f/${KEYFILE}
-    ls -l /usr/local/etc/p2f/${WATCHFILE}
-    ls -l /Library/LaunchDaemons/pcap2flow.plist
+    ls -l /usr/local/bin/query.py
+    ls -l /usr/local/etc/p2f/*
     ls -l /usr/local/share/man/man1/pcap2flow.1
+    ls -l /Library/LaunchDaemons/pcap2flow.plist
 
     echo "stopping flow capture daemon (just in case one is already running)"
     launchctl unload /Library/LaunchDaemons/pcap2flow.plist
@@ -362,6 +298,7 @@ if [ "$sysname" == "Darwin" ]; then
     launchctl load /Library/LaunchDaemons/pcap2flow.plist
 
     echo "...done"
+    echo
     exit
 elif [ "$sysname" == "Linux" ]; then 
     ##
@@ -383,6 +320,39 @@ elif [ "$sysname" == "Linux" ]; then
         fi
     fi
 
+    # Create /usr/local/bin directory if it does not currently exist
+    create_directory /usr/local/bin
+
+    # Create /usr/local/var directory if it does not currently exist
+    create_directory /usr/local/var
+
+    # Create /usr/local/var/p2f directory if it does not currently exist
+    create_directory /usr/local/var/p2f
+
+    # Create /usr/local/var/log directory if it does not currently exist
+    create_directory /usr/local/var/log
+
+    # Create /usr/local/etc directory if it does not currently exist
+    create_directory /usr/local/etc
+
+    # Create /usr/local/etc/p2f directory if it does not currently exist
+    create_directory /usr/local/etc/p2f
+
+    # Create /usr/local/share directory if it does not currently exist
+    create_directory /usr/local/share
+
+    # Create /usr/local/share/man directory if it does not currently exist
+    create_directory /usr/local/share/man
+
+    # Create /usr/local/share/man/man1 directory if it does not currently exist
+    create_directory /usr/local/share/man/man1
+
+    # Create /usr/local/share/joy directory if it does not currently exist
+    create_directory /usr/local/share/joy
+
+    # Create /usr/local/share/joy/data directory if it does not currently exist
+    create_directory /usr/local/share/joy/data
+
     # Stop service, if a previous version is already running
     echo "stopping service (this might take some time)" 
     if [ "$daemon_system" == "sysv" ]; then
@@ -392,86 +362,85 @@ elif [ "$sysname" == "Linux" ]; then
     fi
 
     # Install the binary executable
-    cp bin/pcap2flow /usr/bin/
+    cp bin/pcap2flow /usr/local/bin/
     retval=$?
     if [ $retval -ne "0" ]; then
-        echo "error: could not copy to /usr/bin/"
+        echo "error: could not copy to /usr/local/bin/"
         exit
     fi
 
-    # Create /var/p2f directory if it does not currently exist
-    if [ ! -d /var/p2f ]; then
-	mkdir /var/p2f
-	retval=$?
-	if [ $retval -ne "0" ]; then
-        echo "error: could not make directory /var/p2f"
+    # Install query
+    cp query.py /usr/local/bin/
+    retval=$?
+    if [ $retval -ne "0" ]; then
+        echo "error: could not copy to /usr/local/bin/"
         exit
-	fi
+    fi
+
+    # Install the linux configuration file
+    if [ -f /usr/local/etc/p2f/linux.cfg ]; then
+        echo "warning: file /usr/local/etc/p2f/linux.cfg exists; renaming that file to linux.cfg.bak"
+        mv /usr/local/etc/p2f/linux.cfg /usr/local/etc/p2f/linux.cfg.bak 
     else
-        echo "directory /var/p2f/ already exists"
-    fi
-
-    # Create /etc/p2f directory if it does not currently exist
-    if [ ! -d /etc/p2f ]; then
-        mkdir /etc/p2f
+        cp ${CONFIGFILE} /usr/local/etc/p2f/linux.cfg
         retval=$?
         if [ $retval -ne "0" ]; then
-            echo "error: could not make directory /etc/p2f"
+            echo "error: could not copy to /usr/local/etc/p2f"
             exit
         fi
-    else
-        echo "directory /etc/p2f/ already exists"
     fi
 
-    if [ -f /etc/p2f/linux.cfg ]; then
-        echo "warning: file /etc/p2f/linux.cfg exists; renaming that file to linux.cfg.bak"
-        mv /etc/p2f/linux.cfg /etc/p2f/linux.cfg.bak 
+    # Install the tls fingerprint file
+    if [ -f /usr/local/etc/p2f/${TLS_FINGERPRINT_FILE} ]; then
+        echo "file /usr/local/etc/p2f/${TLS_FINGERPRINT_FILE} exists; not installing tls fingerprint file"
     else
-        cp ${CONFIGFILE} /etc/p2f/linux.cfg
+        cp ${TLS_FINGERPRINT_FILE} /usr/local/etc/p2f/
         retval=$?
         if [ $retval -ne "0" ]; then
-            echo "error: could not copy to /etc/p2f"
+            echo "error: could not copy ${TLS_FINGERPRINT_FILE} to /usr/local/etc/p2f"
             exit
         fi
     fi
 
     # Install the anonymization file
-    if [ -f /etc/p2f/${ANONFILE} ]; then
-        echo "file /etc/p2f/${ANONFILE} exists; not installing subnet file"
+    if [ -f /usr/local/etc/p2f/${ANONFILE} ]; then
+        echo "file /usr/local/etc/p2f/${ANONFILE} exists; not installing subnet file"
     else
-        cp ${ANONFILE} /etc/p2f/
+        cp ${ANONFILE} /usr/local/etc/p2f/
         retval=$?
         if [ $retval -ne "0" ]; then
-            echo "error: could not copy to /etc/p2f"
+            echo "error: could not copy to /usr/local/etc/p2f"
             exit
         fi
     fi
 
     # Install the ssh key file
-    mv ${KEYFILE} /etc/p2f/
+    mv ${KEYFILE} /usr/local/etc/p2f/
     retval=$?
     if [ $retval -ne "0" ]; then
-        echo "error: could not move ${KEYFILE} to /etc/p2f"
+        echo "error: could not move ${KEYFILE} to /usr/local/etc/p2f"
         exit
     fi
-    chmod 600 /etc/p2f/${KEYFILE}
+    chmod 600 /usr/local/etc/p2f/${KEYFILE}
 
-    # Install the watch file
-    if [ -f /etc/p2f/${WATCHFILE} ]; then
-        echo "file /etc/p2f/${WATCHFILE} exists; overwriting with recent file"
-    fi
-    cp ${WATCHFILE} /etc/p2f/
-    retval=$?
-    if [ $retval -ne "0" ]; then
-        echo "error: could not copy to /etc/p2f"
-        exit
+    if [ "${WATCHFILE}" != "" ]; then
+        # Install the watch file
+        if [ -f /usr/local/etc/p2f/${WATCHFILE} ]; then
+            echo "file /usr/local/etc/p2f/${WATCHFILE} exists; overwriting with recent file"
+        fi
+        cp ${WATCHFILE} /usr/local/etc/p2f/
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not copy to /usr/local/etc/p2f"
+            exit
+        fi
     fi
 
     # Install the manpage documentation
-    cp doc/pcap2flow.1 /usr/share/man/man1/
+    cp doc/pcap2flow.1 /usr/local/share/man/man1/
     retval=$?
     if [ $retval -ne "0" ]; then
-        echo "error: could not copy to /usr/share/man/man1/"
+        echo "error: could not copy to /usr/local/share/man/man1/"
         exit
     fi
     mandb >/dev/null
@@ -481,28 +450,10 @@ elif [ "$sysname" == "Linux" ]; then
         # exit
     fi
 
-    # Install query
-    cp query.py /usr/bin/
+    cp data/* /usr/local/share/joy/data
     retval=$?
     if [ $retval -ne "0" ]; then
-        echo "error: could not copy to /usr/bin/"
-        exit
-    fi
-
-    if [ ! -d "/usr/share/joy" ]; then
-        mkdir /usr/share/joy
-    else
-        echo "directory /usr/share/joy already exists"
-    fi
-    if [ ! -d "/usr/share/joy/data" ]; then
-        mkdir /usr/share/joy/data
-    else
-        echo "directory /usr/share/joy/data already exists"
-    fi
-    cp data/* /usr/share/joy/data
-    retval=$?
-    if [ $retval -ne "0" ]; then
-        echo "error: could not copy data files into directory /usr/share/joy/data"
+        echo "error: could not copy data files into directory /usr/local/share/joy/data"
         exit
     fi
 
@@ -565,14 +516,11 @@ elif [ "$sysname" == "Linux" ]; then
     fi
 
     # List all the installed files
-    ls -l /usr/bin/pcap2flow
-    ls -l /usr/bin/query.py
-    ls -l /usr/share/joy/data/*
-    ls -l /etc/p2f/linux.cfg
-    ls -l /etc/p2f/${ANONFILE}
-    ls -l /etc/p2f/${KEYFILE}
-    ls -l /etc/p2f/${WATCHFILE}
-    ls -l /usr/share/man/man1/pcap2flow.1
+    ls -l /usr/local/bin/pcap2flow
+    ls -l /usr/local/bin/query.py
+    ls -l /usr/local/etc/p2f/*
+    ls -l /usr/local/share/joy/data/*
+    ls -l /usr/local/share/man/man1/pcap2flow.1
 
     if [ "$daemon_system" == "sysv" ]; then
         ls -l /etc/init.d/pcap2flow
@@ -584,7 +532,7 @@ elif [ "$sysname" == "Linux" ]; then
     fi
 
     echo "done" 
-    
+    echo
 else
 
     echo "error: unknown system ($sysname)"
diff --git a/uninstall-sh b/uninstall-sh
--- a/uninstall-sh
+++ b/uninstall-sh
@@ -7,6 +7,35 @@
 #
 # uninstaller for pcap2flow and related files
 
+echo
+echo PCAP2FLOW UNINSTALL-SH
+echo --------------------
+echo
+
+delete_file () {
+    if [ -f $1 ]; then
+        rm $1
+        retval=$?
+        if [ $retval != "0" ]; then
+            echo "error: could not delete file $1"
+        else
+            echo "deleted file $1"
+        fi
+    fi
+}
+
+delete_directory () {
+    if [ -d $1 ]; then
+        rm -rf $1
+        retval=$?
+        if [ $retval != "0" ]; then
+            echo "error: could not delete directory $1"
+        else
+            echo "deleted directory $1"
+        fi
+    fi
+}
+
 sysname=`uname -s`
 
 if [ "$sysname" == "Darwin" ]; then
@@ -19,45 +48,15 @@ if [ "$sysname" == "Darwin" ]; then
     launchctl unload /Library/LaunchDaemons/pcap2flow.plist
 
     # Delete the application files
-    if [ -f /usr/local/bin/pcap2flow ]; then
-        rm /usr/local/bin/pcap2flow
-        retval=$?
-        if [ $retval != "0" ]; then
-            echo "error: could not delete file /usr/local/bin/pcap2flow"
-        else
-            echo "deleted file /usr/local/bin/pcap2flow"
-        fi
-    fi
+    delete_file /usr/local/bin/pcap2flow
 
-    if [ -d /usr/local/etc/p2f ]; then
-        rm -rf /usr/local/etc/p2f
-        retval=$?
-        if [ $retval != "0" ]; then
-            echo "error: could not delete directory /usr/local/etc/p2f"
-        else
-            echo "deleted directory /usr/local/etc/p2f"
-        fi
-    fi
+    delete_file /usr/local/bin/query.py
 
-    if [ -f /Library/LaunchDaemons/pcap2flow.plist ]; then
-        rm /Library/LaunchDaemons/pcap2flow.plist
-        retval=$?
-        if [ $retval != "0" ]; then
-            echo "error: could not delete file /Library/LaunchDaemons/pcap2flow.plist"
-        else
-            echo "deleted file /Library/LaunchDaemons/pcap2flow.plist"
-        fi
-    fi
+    delete_directory /usr/local/etc/p2f
 
-    if [ -f /usr/local/share/man/man1/pcap2flow.1 ]; then
-        rm /usr/local/share/man/man1/pcap2flow.1
-        retval=$?
-        if [ $retval != "0" ]; then
-            echo "error: could not delete file /usr/local/share/man/man1/pcap2flow.1"
-        else
-            echo "deleted file /usr/local/share/man/man1/pcap2flow.1"
-        fi
-    fi
+    delete_file /Library/LaunchDaemons/pcap2flow.plist
+
+    delete_file /usr/local/share/man/man1/pcap2flow.1
 
     echo "... done"
     echo
@@ -95,87 +94,24 @@ elif [ "$sysname" == "Linux" ]; then
     fi
 
     # Delete the application files
-    if [ -f /usr/bin/pcap2flow ]; then
-        rm /usr/bin/pcap2flow
-        retval=$?
-        if [ $retval != "0" ]; then
-            echo "error: could not delete file /usr/bin/pcap2flow"
-        else
-            echo "deleted file /usr/bin/pcap2flow"
-        fi
-    fi
+    delete_file /usr/local/bin/pcap2flow
 
-    if [ -f /usr/bin/query.py ]; then
-        rm /usr/bin/query.py
-        retval=$?
-        if [ $retval != "0" ]; then
-            echo "error: could not delete file /usr/bin/query.py"
-        else
-            echo "deleted file /usr/bin/query.py"
-        fi
-    fi
+    delete_file /usr/local/bin/query.py
 
-    if [ -d /usr/share/joy/data ]; then
-        rm -rf /usr/share/joy/data
-        retval=$?
-        if [ $retval != "0" ]; then
-            echo "error: could not delete directory /usr/share/joy/data"
-        else
-            echo "deleted directory /usr/share/joy/data"
-        fi
-    fi
+    delete_directory /usr/local/etc/p2f
 
-    if [ -d /etc/p2f ]; then
-        rm -rf /etc/p2f
-        retval=$?
-        if [ $retval != "0" ]; then
-            echo "error: could not delete directory /etc/p2f"
-        else
-            echo "deleted directory /etc/p2f"
-        fi
-    fi
+    delete_directory /usr/local/share/joy
+    delete_directory /usr/local/share/joy/data
 
-    if [ -f /usr/share/man/man1/pcap2flow.1 ]; then
-        rm /usr/share/man/man1/pcap2flow.1
-        retval=$?
-        if [ $retval != "0" ]; then
-            echo "error: could not delete file /usr/share/man/man1/pcap2flow.1"
-        else
-            echo "deleted file /usr/share/man/man1/pcap2flow.1"
-        fi
-    fi
+    delete_file /usr/local/share/man/man1/pcap2flow.1
 
     # Delete daemon specific files
     if [ "$daemon_system" == "sysv" ]; then
-        if [ -f /etc/init.d/pcap2flow ]; then
-            rm /etc/init.d/pcap2flow
-            retval=$?
-            if [ $retval != "0" ]; then
-                echo "error: could not delete file /etc/init.d/pcap2flow"
-            else
-                echo "deleted file /etc/init.d/pcap2flow"
-            fi
-        fi
-    elif [ "$daemon_system" == "systemd" ]; then
-        if [ -f /etc/systemd/system/pcap2flow.service ]; then
-            rm /etc/systemd/system/pcap2flow.service
-            retval=$?
-            if [ $retval != "0" ]; then
-                echo "error: could not delete file /etc/systemd/system/pcap2flow.service"
-            else
-                echo "deleted file /etc/systemd/system/pcap2flow.service"
-            fi
-        fi
+        delete_file /etc/init.d/pcap2flow
 
-        if [ -f /etc/systemd/system/pcap2flow.service.d/pcap2flow_env.conf ]; then
-            rm /etc/systemd/system/pcap2flow.service
-            retval=$?
-            if [ $retval != "0" ]; then
-                echo "error: could not delete file /etc/systemd/system/pcap2flow.service.d/pcap2flow_env.conf"
-            else
-                echo "deleted file /etc/systemd/system/pcap2flow.service.d/pcap2flow_env.conf"
-            fi
-        fi
+    elif [ "$daemon_system" == "systemd" ]; then
+        delete_file /etc/systemd/system/pcap2flow.service
+        delete_directory /etc/systemd/system/pcap2flow.service.d
     fi
 
     echo "... done"
