install-sh now uses curl when available, wget otherwise

diff --git a/install-sh b/install-sh
--- a/install-sh
+++ b/install-sh
@@ -121,13 +121,31 @@ if [ "${WATCHFILE}" == "" ]; then
     #
     WATCHFILE=ip-filter.blf
 
+    # find a downloader program
+    command -v curl -h >/dev/null 2>&1
+    retval=$?
+    if [ $retval -ne "0" ]; then
+	command -v wget -h >/dev/null 2>&1
+	retval=$?
+	if [ $retval -ne "0" ]; then
+	    echo "error: did not find either curl or wget, cannot download $WATCHFILE"
+	    exit
+	else
+	    downloader=wget
+	fi
+    else
+	echo "found curl"
+	downloader=curl
+    fi
+    echo "using program $downloader"
+
     # download the current public list of malware IP addresses from
     # Talos (the Sourcefire/Cisco threat intelligence team) - note
     # that this file changes daily, so don't rely on it if you don't
     # update it - and install it as a malware watchlist file
     # 
     echo "downloading ip-filter.blf ... "
-    wget http://www.talosintel.com/feeds/ip-filter.blf -O ./ip-filter.blf
+    wget http://www.talosintel.com/feeds/ip-filter.blf -o ./ip-filter.blf
     retval=$?
     if [ $retval -ne "0" ]; then
 	echo "error: could not download ${WATCHFILE}"
