WIP systemd daemon support 4
Changes for MacOSX install/uninstall

diff --git a/install-sh b/install-sh
--- a/install-sh
+++ b/install-sh
@@ -180,6 +180,19 @@ else
     NEWKEY=1
 fi
 
+create_directory () {
+    if [ ! -d $1 ]; then
+        mkdir $1
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not make directory $1"
+            exit
+        fi
+    else
+        echo "directory $1 already exists"
+    fi
+}
+
 sysname=`uname -s`
 
 if [ "$sysname" == "Darwin" ]; then
@@ -188,106 +201,168 @@ if [ "$sysname" == "Darwin" ]; then
     ##
     echo "found $sysname (Mac OS X), installing pcap2flow ..."
 
-    cp bin/pcap2flow /usr/libexec/
+    # Create /usr/local/bin directory if it does not currently exist
+    if [ ! -d /usr/local/bin ]; then
+        mkdir /usr/local/bin
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not make directory /usr/local/bin"
+            exit
+        fi
+    else
+        echo "directory /usr/local/bin already exists"
+    fi
+
+    # Create /usr/local/var directory if it does not currently exist
+    if [ ! -d /usr/local/var ]; then
+        mkdir /usr/local/var
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not make directory /usr/local/var"
+            exit
+        fi
+    else
+        echo "directory /usr/local/var already exists"
+    fi
+
+    # Create /usr/local/var/p2f directory if it does not currently exist
+    if [ ! -d /usr/local/var/p2f ]; then
+        mkdir /usr/local/var/p2f
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not make directory /usr/local/var/p2f"
+            exit
+        fi
+    else
+        echo "directory /usr/local/var/p2f already exists"
+    fi
+
+    # Create /usr/local/etc directory if it does not currently exist
+    if [ ! -d /usr/local/etc ]; then
+        mkdir /usr/local/etc
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not make directory /usr/local/etc"
+            exit
+        fi
+    else
+        echo "directory /usr/local/etc already exists"
+    fi
+
+    # Create /usr/local/etc/p2f directory if it does not currently exist
+    if [ ! -d /usr/local/etc/p2f ]; then
+        mkdir /usr/local/etc/p2f
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not make directory /usr/local/etc/p2f"
+            exit
+        fi
+    else
+        echo "directory /usr/local/etc/p2f already exists"
+    fi
+
+    # Create /usr/local/share directory if it does not currently exist
+    if [ ! -d /usr/local/share ]; then
+        mkdir /usr/local/share
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not make directory /usr/local/share"
+            exit
+        fi
+    else
+        echo "directory /usr/local/share already exists"
+    fi
+
+    # Create /usr/local/share/man directory if it does not currently exist
+    create_directory /usr/local/share/man
+
+    # Create /usr/local/share/man/man1 directory if it does not currently exist
+    create_directory /usr/local/share/man/man1
+
+    # Install the binary executable
+    cp bin/pcap2flow /usr/local/bin
     retval=$?
     if [ $retval -ne "0" ]; then
-	echo "error: could not copy to /usr/libexec/"
-	exit
+        echo "error: could not copy bin/pcap2flow to /usr/local/bin"
+        exit
     fi
 
-    if [ ! -d /var/p2f ]; then
-	mkdir /var/p2f
-	retval=$?
-	if [ $retval -ne "0" ]; then
-	    echo "error: could not make directory /var/p2f"
-	    exit
-	fi
+    if [ -f /usr/local/etc/p2f/macosx.cfg ]; then
+        echo "warning: file /usr/local/etc/p2f/macosx.cfg exists; renaming that file to macosx.cfg.bak"
+        mv /usr/local/etc/p2f/macosx.cfg /usr/local/etc/p2f/macosx.cfg.bak 
     else
-	echo "directory /var/p2f/ already exists"
+        cp ${MACOSX_CONFIGFILE} /usr/local/etc/p2f/macosx.cfg
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not copy ${MACOSX_CONFIGFILE} to /usr/local/etc/p2f"
+            exit
+        fi
     fi
 
-    if [ ! -d /etc/p2f ]; then
-	mkdir /etc/p2f
-	retval=$?
-	if [ $retval -ne "0" ]; then
-	    echo "error: could not make directory /etc/p2f"
-	    exit
-	fi
+    # Install the anonymization file
+    if [ -f /usr/local/etc/p2f/${ANONFILE} ]; then
+        echo "file /usr/local/etc/p2f/${ANONFILE} exists; not installing anonymization subnet file"
     else
-	echo "directory /etc/p2f/ already exists"
+        cp ${ANONFILE} /usr/local/etc/p2f/
+        retval=$?
+        if [ $retval -ne "0" ]; then
+            echo "error: could not copy ${ANONFILE} to /usr/local/etc/p2f"
+            exit
+        fi
     fi
 
-    if [ -f /etc/p2f/macosx.cfg ]; then
-	echo "warning: file /etc/p2f/macosx.cfg exists; renaming that file to macosx.cfg.bak"
-	mv /etc/p2f/macosx.cfg /etc/p2f/macosx.cfg.bak 
-    else
-	cp ${MACOSX_CONFIGFILE} /etc/p2f/macosx.cfg
-	retval=$?
-	if [ $retval -ne "0" ]; then
-	    echo "error: could not copy to /etc/p2f"
-	    exit
-	fi
-    fi
-
-    if [ -f /etc/p2f/${ANONFILE} ]; then
-	echo "file /etc/p2f/${ANONFILE} exists; not installing anonymization subnet file"
-    else
-	cp ${ANONFILE} /etc/p2f/
-	retval=$?
-	if [ $retval -ne "0" ]; then
-	    echo "error: could not copy to /etc/p2f"
-	    exit
-	fi
-    fi
-    mv ${KEYFILE} /etc/p2f/
+    # Install the ssh key file
+    mv ${KEYFILE} /usr/local/etc/p2f/
     retval=$?
     if [ $retval -ne "0" ]; then
-	echo "error: could not move ${KEYFILE} to /etc/p2f"
-	exit
+        echo "error: could not move ${KEYFILE} to /usr/local/etc/p2f"
+        exit
     fi
-    chmod 600 /etc/p2f/${KEYFILE}
+    chmod 600 /usr/local/etc/p2f/${KEYFILE}
 
-   if [ -f /etc/p2f/${WATCHFILE} ]; then
-	echo "file /etc/p2f/${WATCHFILE} exists; overwriting with recent file"
-   fi
-   cp ${WATCHFILE} /etc/p2f/
-   retval=$?
-   if [ $retval -ne "0" ]; then
-       echo "error: could not copy to /etc/p2f"
-       exit
-   fi
-
-    cp pcap2flow.plist /System/Library/LaunchDaemons/
+    # Install the watch file
+    if [ -f /usr/local/etc/p2f/${WATCHFILE} ]; then
+        echo "file /etc/p2f/${WATCHFILE} exists; overwriting with recent file"
+    fi
+    cp ${WATCHFILE} /usr/local/etc/p2f/
     retval=$?
     if [ $retval -ne "0" ]; then
-	echo "error: could not copy to /System/Library/LaunchDaemons/"
-	exit
+        echo "error: could not copy ${WATCHFILE} to /usr/local/etc/p2f"
+        exit
     fi
 
-    cp doc/pcap2flow.1 /usr/share/man/man1/
+    # Install the Launchd script for daemon management
+    cp pcap2flow.plist /Library/LaunchDaemons/
     retval=$?
     if [ $retval -ne "0" ]; then
-	echo "error: could not copy to /usr/share/man/man1/ (man page will be unavailable)"
-	exit
+        echo "error: could not copy pcap2flow.plist to /Library/LaunchDaemons"
+        exit
     fi
 
-    ls -l /usr/libexec/pcap2flow
-    ls -l /etc/p2f/macosx.cfg
-    ls -l /etc/p2f/${ANONFILE}
-    ls -l /etc/p2f/${KEYFILE}
-    ls -l /etc/p2f/${WATCHFILE}
-    ls -l /System/Library/LaunchDaemons/pcap2flow.plist
-    ls -l /usr/share/man/man1/pcap2flow.1
-    echo "done"
+    # Install the manpage documentation
+    cp doc/pcap2flow.1 /usr/local/share/man/man1/
+    retval=$?
+    if [ $retval -ne "0" ]; then
+        echo "error: could not copy to /usr/local/share/man/man1 (man page will be unavailable)"
+        exit
+    fi
+
+    ls -l /usr/local/bin/pcap2flow
+    ls -l /usr/local/etc/p2f/macosx.cfg
+    ls -l /usr/local/etc/p2f/${ANONFILE}
+    ls -l /usr/local/etc/p2f/${KEYFILE}
+    ls -l /usr/local/etc/p2f/${WATCHFILE}
+    ls -l /Library/LaunchDaemons/pcap2flow.plist
+    ls -l /usr/local/share/man/man1/pcap2flow.1
 
     echo "stopping flow capture daemon (just in case one is already running)"
-    launchctl unload /System/Library/LaunchDaemons/pcap2flow.plist
+    launchctl unload /Library/LaunchDaemons/pcap2flow.plist
 
     echo "starting flow capture daemon"
-    launchctl load /System/Library/LaunchDaemons/pcap2flow.plist
+    launchctl load /Library/LaunchDaemons/pcap2flow.plist
 
+    echo "...done"
     exit
-
 elif [ "$sysname" == "Linux" ]; then 
     ##
     # Linux operating system detected
@@ -309,11 +384,10 @@ elif [ "$sysname" == "Linux" ]; then
     fi
 
     # Stop service, if a previous version is already running
+    echo "stopping service (this might take some time)" 
     if [ "$daemon_system" == "sysv" ]; then
-        echo "stopping service (this might take some time)" 
         service pcap2flow stop 
     elif [ "$daemon_system" == "systemd" ]; then
-        echo "stopping service (this might take some time)" 
         systemctl stop pcap2flow.service
     fi
 
