Moved python setup.py to Linux section instead of Darwin

diff --git a/install/install-sh b/install/install-sh
--- a/install/install-sh
+++ b/install/install-sh
@@ -244,20 +244,7 @@ if [ "$sysname" == "Darwin" ]; then
         echo "Running pip install ${APP_ROOT}/sleuth/"
         pip install ${APP_ROOT}/sleuth/
     else
-	cd ${APP_ROOT}/sleuth
-	echo "Running python setup.py bdist --format=gztar"
-	python setup.py bdist --format=gztar
-        if [ $retval -ne "0" ]; then
-            echo "error: could not run python setup.py for sleuth"
-            exit 1
-        fi
-        SLEUTHFILE="${APP_ROOT}/sleuth/dist/sleuth-0.1.linux-${ARCH}.tar.gz"
-	if [ -f $SLEUTHFILE ]; then
-            tar -C $PREFIX xf $SLEUTHFILE
-	else
-            echo "Cannot find sleuth tarball $SLEUTHFILE"
-            exit 1
-	fi
+        pip install -t $PREFIX/lib/python ${APP_ROOT}/sleuth/
     fi
 
     # Install the configuration file
@@ -445,7 +432,20 @@ elif [ "$sysname" == "Linux" ]; then
     if [ -z "$PKGBUILD" ]; then
         pip install ${APP_ROOT}/sleuth/
     else
-        pip install -t $PREFIX/lib/python ${APP_ROOT}/sleuth/
+	cd ${APP_ROOT}/sleuth
+	echo "Running python setup.py bdist --format=gztar"
+	python setup.py bdist --format=gztar
+        if [ $retval -ne "0" ]; then
+            echo "error: could not run python setup.py for sleuth"
+            exit 1
+        fi
+        SLEUTHFILE="${APP_ROOT}/sleuth/dist/sleuth-0.1.linux-${ARCH}.tar.gz"
+	if [ -f $SLEUTHFILE ]; then
+            tar -xf $SLEUTHFILE -C $BUILDROOT
+	else
+            echo "Cannot find sleuth tarball $SLEUTHFILE"
+            exit 1
+	fi
     fi
 
     # Install the configuration file
